# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

discrepancyExact <- function(r_points) {
    .Call(`_dandy_discrepancyExact`, r_points)
}

discrepancyGWW <- function(r_points, r_iter, r_max_trials) {
    .Call(`_dandy_discrepancyGWW`, r_points, r_iter, r_max_trials)
}

